apiVersion: v1
kind: Pod
metadata:
  name: "web-test"
spec:
      containers:
        - image: "mcr.microsoft.com/dotnet/core/samples:aspnetapp"
          name: api-test
          env:
            - name: ASPNETCORE_URLS
              value: "http://+:8080"
          ports:
          - containerPort: 8080
            protocol: TCP
          resources:
            requests:
              memory: "512Mi"
              cpu: "200m"
            limits:
              memory: "1024Mi"
              cpu: "1000m"
          securityContext:
            runAsUser: 1000
            privileged: false
            allowPrivilegeEscalation: false
            capabilities:
              add: ["SYS_TIME"]