apiVersion: v1
kind: Pod
metadata:
  name: nginx-test
spec:
  containers:
    - name:  nginx-test
      image: nginx
      resources:
        requests:
          memory: "512Mi"
          cpu: "200m"
        limits:
          memory: "1024Mi"
          cpu: "1000m"
      securityContext:
        privileged: false