apiVersion: v1
kind: LimitRange
metadata:
  name: compute-resources-per-container
spec:
  limits:
  - max:
      cpu: "1000m"
      memory: "2Gi"
    min:
      cpu: "100m"
      memory: "99Mi"
    default:
      cpu: "500m"
      memory: "1024Mi"
    defaultRequest:
      cpu: "250m"
      memory: "512Mi"
    type: Container